### ISSUE TITLE
automatic builds

### ISSUE THREAD

**Issue by jstrube** [GooFit/Minuit2#5]
I also have a standalone version of Minuit2 from the ROOT distro. It is automatically being built for a variety of platforms, please see here:
https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases
This is accomplished using https://binarybuilder.org/
The build script is here: https://github.com/JuliaPackaging/Yggdrasil/tree/master/M/Minuit2 (with a patch)

There is nothing that needs to be done here, I just wanted to give you a heads up, because it may be useful for you to distribute your binaries that way.
Also randomly flagging @HDembinski directly, since he was the last commiter to iminuit on record, and it may be useful for a python package to distribute binaries directly and not impose a C++ compiler on their users.
Hope it's useful.

**Comment by HDembinski** [comment]
Hi, I am not only the last committer but also the maintainer of iminuit. We ship iminuit as binary wheels to people. We do this with Azure-based deployment scripts that Henry has set up. So while you cannot get MINUIT2 as a binary, you can get iminuit as a binary. Thank you for the link to binarybuilder.org, I was not aware of this. This sounds interesting.

**Comment by HDembinski** [comment]
@henryiii I think we can close this?

**Comment by henryiii** [comment]
Added a note based on the text above to the wiki, thanks! Yes, we can close.

**Comment by henryiii** [comment]
See https://github.com/GooFit/Minuit2/wiki
