### ISSUE TITLE
OMP CMake flag

### ISSUE THREAD

**Issue by andrewfowlie** [GooFit/Minuit2#7]
I'm a bit confused about the required CMake flag for open MPI. The README.md and CMakeLists.txt seem to both indicate `minuit2_omp`,

https://github.com/GooFit/Minuit2/blob/ec87e40262427256a972a450a7ea4ce53913f251/CMakeLists.txt#L14

When running CMake, this flag seems to result in the info
```
-- The following packages have been found:

 * OpenMP, Parallel compiler directives, <http://www.openmp.org>
   Parallel FCN calls (Thread safe FCNs only)
```

Do I also need `minuit2_openmp`, which appears here:

https://github.com/GooFit/Minuit2/blob/ec87e40262427256a972a450a7ea4ce53913f251/StandAlone.cmake#L158

When running CMake, this flag seems to result in the info
```
-- The following features have been enabled:

 * minuit2_openmp, OpenMP (Thread safe FCNs only)
```

I wonder whether both these flags were supposed to have the same name?

**Comment by henryiii** [comment]
Yes, I believe this was a typo on my part. Would you like to make a PR to https://github.com/root-project/root , or would you like me to?

**Comment by henryiii** [comment]
And, for now, no, you only need `minuit2_omp`, `minuit2_openmp` would only enable the pretty feature list printout at the end, it does not have any other effect.

**Comment by andrewfowlie** [comment]
Thanks, I'll make the PR
